<?php
/**
 * @var \Improntus\WhatsappContact\Block\WhatsApp $block
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<style>
    /*=========================================
    ESTILOS PARA POPUPREDES ESCRITORIO
    =========================================== */
    .redes{
        margin: 0 !important;
        padding: 0 !important;
        position: fixed !important;
        z-index: 16000160 !important;
        text-align: center !important;
        height: 90px;
        width: 60px;
        visibility: visible;
        transition: none !important;
    }
    .contenedor_redes{
        margin: 0;
        padding: 0;
        border: 0;
        position: fixed;
        z-index: 16000160;
        bottom: 0;
        text-align: center;
        overflow: hidden;
    }
    /*  ESTILOS PARA UBICACION DE POPUP */
    .bottom-right{
        right: 0;
        bottom: 0;
    }

    .bottom-left{
        left: 0;
        bottom: 0;
    }

    .top-right{
        top : 0;
        right: 0;
    }
    .top-left{
        top : 0;
        left: 0;
    }
    /*  ESTILOS PARA EL CONTENIDO DEL POPUP */
    .bottom-left #mensaje-popup,.top-left #mensaje-popup{
        float: right;
        margin-left: 10px;
    }
    .bottom-right #mensaje-popup,.top-right #mensaje-popup{
        float: left;
        margin-right: 10px;
    }
    .bottom-right #mensaje-popup.animacion-popup-in,.top-right #mensaje-popup.animacion-popup-in{
        -webkit-animation-name: callToActionRight;
        -moz-animation-name: callToActionRight;
        -o-animation-name: callToActionRight;
        animation-name: callToActionRight;
        -webkit-animation-duration: .8s;
        -moz-animation-duration: .8s;
        -o-animation-duration: .8s;
        animation-duration: .8s;
        -webkit-animation-fill-mode: forwards;
        -moz-animation-fill-mode: forwards;
        -o-animation-fill-mode: forwards;
        animation-fill-mode: forwards;
    }
    .bottom-right #mensaje-popup.animacion-popup-out,.top-right #mensaje-popup.animacion-popup-out{
        -webkit-animation-name: callToActionRight;
        -moz-animation-name: callToActionRight;
        -o-animation-name: callToActionRight;
        animation-name: callToActionRight;
        -webkit-animation-duration: .8s;
        -moz-animation-duration: .8s;
        -o-animation-duration: .8s;
        animation-duration: .8s;
        -webkit-animation-fill-mode: forwards;
        -moz-animation-fill-mode: forwards;
        -o-animation-fill-mode: forwards;
        animation-fill-mode: forwards;
        -webkit-animation-direction: reverse;
        -moz-animation-direction: reverse;
        -o-animation-direction: reverse;
        animation-direction: reverse;
    }
    #mensaje-popup{
        position: relative;
        top: 29px;
        box-shadow: 2px 2px 13px rgba(0,0,0,0.1);
        border: 1px solid #e2e2e2;
        border-radius: 5px;
        background: white;
        cursor: pointer;
    }
    .mensaje-hide{
        display: none!important;
    }

    #mensaje-popup a .contenido-popup{
        padding: 5px 10px 5px 10px;
        line-height: 18px;
        max-height: 45px;
        max-width: 160px;
        overflow: hidden;
        word-wrap: break-word;
        font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
        font-size: 14px;
    }
    .bottom-right #mensaje-popup:before{
        z-index: 2;
    }
    .bottom-right #mensaje-popup:before, .bottom-right #mensaje-popup:after,.top-right #mensaje-popup:before,
    .top-right #mensaje-popup:after{
        content: '';
        position: absolute;
        background: white;
        border-bottom: 1px solid #e2e2e2;
        border-right: 1px solid #e2e2e2;
        right: -5px;
        top: 50%;
        margin-top: -4px;
        width: 8px;
        height: 8px;
        z-index: 1;
        -ms-transform: rotate(-45deg);
        -webkit-transform: rotate(-45deg);
        -moz-transform: rotate(-45deg);
        -o-transform: rotate(-45deg);
        transform: rotate(-45deg);
    }
    .bottom-left #mensaje-popup:before, .bottom-left #mensaje-popup:after,.top-left #mensaje-popup:before,
    .top-left #mensaje-popup:after{
         content: '';
         position: absolute;
         background: white;
         border-top: 1px solid #e2e2e2;
         border-left: 1px solid #e2e2e2;
         left: -5px;
         top: 50%;
         margin-top: -4px;
         width: 8px;
         height: 8px;
         z-index: 1;
         -ms-transform: rotate(-45deg);
         -webkit-transform: rotate(-45deg);
         -moz-transform: rotate(-45deg);
         -o-transform: rotate(-45deg);
         transform: rotate(-45deg);
     }
    /* ESTILOS PARA BTN RED */
    div.redes.bottom-right div.btn-red,div.redes.top-right div.btn-red{
        right: 10px;
        float: right;
    }
    div.redes.bottom-left div.btn-red,div.redes.top-left div.btn-red{
        left: 10px;
        float: left;
    }
    div.redes div.btn-red{
        margin: 10px;
        margin-bottom: 20px;
        padding: 0;
        border: 0;
        position: relative;
        bottom: 3px;
        text-align: center;
    }
    div.redes div.btn-red>a.icono-red{
        display: none;
        text-decoration: none;
        font-weight: normal;
        margin-top: 14px;
        position: relative;
        outline: none;
        min-width: 55px;
    }
    div.redes div.btn-red>a.icono-red.icono-red-activo{
        display: block;
    }
    div.redes div.btn-red>a.icono-red div.btn-icono.bg-whatsapp{
        background-color: #4dc247;
    }
    div.redes.bottom-right div.btn-red>a.icono-red div.btn-icono,div.redes.top-right div.btn-red >
    a.icono-red div.btn-icono{
        float: right;
    }
    div.redes.bottom-left div.btn-red>a.icono-red div.btn-icono,div.redes.top-left div.btn-red >
    a.icono-red div.btn-icono{
        float: left;
    }
    div.redes div.btn-red>a.icono-red div.btn-icono{
        float: left;
        height: 50px;
        width: 50px;
        border-radius: 50%;
        overflow: hidden;
        box-shadow: 2px 2px 6px rgba(0,0,0,0.4);
        font-size: 28px;
        text-align: center;
        line-height: 50px;
        color: white;
    }
    div.redes div.btn-red>a.icono-red.icono-red-activo div.btn-icono>div{
        height: 100%;
        width: 100%;
        -moz-transition: transform 0.4s ease;
        -o-transition: transform 0.4s ease;
        -webkit-transition: transform 0.4s ease;
        transition: transform 0.4s ease;
    }
    div.redes div.btn-red>a.icono-red div.btn-icono .svg-icon{
        display: inline;
    }
    div.redes div.btn-red>a.icono-red div.btn-icono svg{
        fill: white;
        width: 41px;
        height: 50px;
    }
    div.redes div.btn-red>a.icono-red:hover div.btn-icono{
        box-shadow : 2px 2px 11px rgba(0,0,0,0.7);
    }

    /* ===================================================
    TABLET HORIZONTAL (1024px)
    ====================================================== */
    @media (max-width: 1199px) and (min-width: 992px) {

    }

    /* ===================================================
    TABLET VERTICAL (768px)
    ====================================================== */
    @media (max-width: 991px) and (min-width: 768px) {

    }

    /* ===================================================
    MOvIL HORIZONTAL (576 px)
    ====================================================== */
    @media (max-width: 767px) and (min-width: 576px) {

    }

    /* ===================================================
    MOVIL VERTICAL (320px)
    ====================================================== */
    @media (max-width: 575px) {

    }
</style>

<div id="contendedor-redes" class="contenedor_redes <?= $escaper->escapeHtml($block->getPosition())?>">
    <div id="popup-placement" class="popup-slide"></div>
    <div id="mensaje-popup" class=""  style="top: 29px;">
        <a  href="#">
            <div class="contenido-popup"><?= $escaper->escapeHtml($block->getPopUpText()) ?></div>
        </a>
    </div>
    <div id="btn-red" class="btn-red">
        <a class=" icono-red icono-red-activo" href="https://api.whatsapp.com/send?phone=<?= $escaper->escapeHtml(
            $block->getCountryCode() . $block->getNumber());?>&text=<?= ($block->getMessageText()!='') ?
            $escaper->escapeHtml($block->getMessageText()) : ''?>">
            <div class=" btn-icono bg-whatsapp">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                         viewBox="0 0 32 32" class="svg-whatsapp svg-icon">
                        <path d=" M19.11 17.205c-.372 0-1.088 1.39-1.518 1.39a.63.63 0 0 1-.315-.1c-.802-.402-1.504-.817-2.163-1.447-.545-.516-1.146-1.29-1.46-1.963a.426.426 0 0 1-.073-.215c0-.33.99-.945.99-1.49 0-.143-.73-2.09-.832-2.335-.143-.372-.214-.487-.6-.487-.187 0-.36-.043-.53-.043-.302 0-.53.115-.746.315-.688.645-1.032 1.318-1.06 2.264v.114c-.015.99.472 1.977 1.017 2.78 1.23 1.82 2.506 3.41 4.554 4.34.616.287 2.035.888 2.722.888.817 0 2.15-.515 2.478-1.318.13-.33.244-.73.244-1.088 0-.058 0-.144-.03-.215-.1-.172-2.434-1.39-2.678-1.39zm-2.908 7.593c-1.747 0-3.48-.53-4.942-1.49L7.793 24.41l1.132-3.337a8.955 8.955 0 0 1-1.72-5.272c0-4.955 4.04-8.995 8.997-8.995S25.2 10.845 25.2 15.8c0 4.958-4.04 8.998-8.998 8.998zm0-19.798c-5.96 0-10.8 4.842-10.8 10.8 0 1.964.53 3.898 1.546 5.574L5 27.176l5.974-1.92a10.807 10.807 0 0 0 16.03-9.455c0-5.958-4.842-10.8-10.802-10.8z"
                              fill-rule="evenodd"></path>
                    </svg>
                </div>
            </div>
        </a>
    </div>
    <div class=" clear"></div>
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            var ubicacion = "<?= $block->getPosition() ?>";

            $('.redes').addClass(ubicacion);
            $('#mensaje-popup').addClass('animacion-popup-in');
            $('.btn-red').mouseenter(function () {
                $('#mensaje-popup').removeClass('animacion-popup-in');
                $('#mensaje-popup').addClass('animacion-popup-out');
                $('#mensaje-popup').addClass('mensaje-hide');
            })
        });

    });
</script>
