<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2026 Improntus (http://www.improntus.com/)
 */

/**
 * @var \Improntus\WhatsappContact\Block\WhatsApp $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$position = $block->getPosition();
?>

<div id="contendedor-redes" class="contenedor_redes <?= $escaper->escapeHtmlAttr($position) ?>">
    <div id="popup-placement" class="popup-slide"></div>
    <div id="mensaje-popup" class="">
        <a href="#">
            <div class="contenido-popup"><?= $escaper->escapeHtml($block->getPopUpText()) ?></div>
        </a>
    </div>
    <div id="btn-red" class="btn-red">
        <a class="icono-red icono-red-activo"
           target="_blank"
           rel="noopener noreferrer"
           href="<?= $escaper->escapeUrl($block->getWhatsappUrl()) ?>">
            <div class="btn-icono bg-whatsapp">
                <i class="wsp"><?= /* @noEscape */ $block->getWhatsappIconSvg() ?></i>
            </div>
        </a>
    </div>
    <div class="clear"></div>
</div>

<?php
$positionJson = json_encode($position);
$script = <<<SCRIPT
require(['jquery'], function ($) {
    'use strict';

    $(function () {
        var position = {$positionJson},
            \$message = $('#mensaje-popup');

        $('.redes').addClass(position);

        $('.btn-red').on('mouseenter', function () {
            \$message.addClass('mensaje-hide');
        });
    });
});
SCRIPT;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>
